from . import fundacupaz_phone
from . import fundacupaz_phone_plan
from . import comisionado_estadal
from . import fundacupaz_cuadrantes
from . import fundacupaz_moto_marca
from . import fundacupaz_moto_modelo
from . import fundacupaz_pc
from . import fundacupaz_fleet
from . import fundacupaz_entes
from . import fundacupaz_inventario